upgrade laterals and boundary conditions
nens/threedi-schema pull request #72
Opened 2024-08-21 10:13 UTC by elisalle

2024-09-03 14:00 UTC, margrietpalm requested changes
The migration and schema changes don't fully match the specifications and there is an issue with changing names. Also there are no changes added to `CHANGES.rst`.

2024-09-04 08:42 UTC, elisalle commented on threedi_schema/migrations/versions/0225_migrate_lateral_boundary_condition_tables.py
> +    "boundary_condition_2d": [
I just tried it out on an sqlite, and got this:
```
spatialite> pragma table_info(boundary_condition_2d);
0|id|INTEGER|1||0
1|display_name|VARCHAR(255)|0||0
2|timeseries|TEXT|0||0
3|type|INTEGER|0||0
4|geom|LINESTRING|1||0
5|code|TEXT|0||0
6|tags|TEXT|0||0
7|time_units|TEXT|0||0
8|interpolate|BOOLEAN|0||0
```
could you send me the sqlite you ran the migration on?

2024-09-04 09:11 UTC, margrietpalm commented on threedi_schema/migrations/versions/0225_migrate_lateral_boundary_condition_tables.py
> +    "boundary_condition_2d": [
Hmm, cannot reproduce that one  any more.

2024-09-04 11:58 UTC, elisalle commented on threedi_schema/domain/models.py
> -        nullable=False,
Regarding the modelchecker check, wouldn't that already be covered by BoundaryCondition1DObjectNumberCheck?

2024-09-04 12:11 UTC, margrietpalm commented on threedi_schema/domain/models.py
> -        nullable=False,
If that check indeed ensures that every `connection_node_id` that is used exists. However, I'm a bit confused by this test; I thought that the `connection_node_id` should match to a `v2_connection_nodes` entry.

2024-09-04 12:15 UTC, elisalle commented on threedi_schema/domain/models.py
> -        nullable=False,
You're right, I misread the check.

2024-09-04 14:05 UTC, elisalle commented on threedi_schema/domain/models.py
> -        nullable=False,
I've added the checks here https://github.com/nens/threedi-modelchecker/commit/c25c2e414aaf76cb8ecdaf07ee86efe5ee642d88

2024-09-04 14:11 UTC, elisalle commented
> Also there are no changes added to `CHANGES.rst`.
the changelog has now been updated

2024-09-09 06:03 UTC, margrietpalm approved these changes

2024-09-09 07:50 UTC, merged